name: Build the middleware application just to check if it compiles.
on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"
  workflow_dispatch:
jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go, cache and check for latest version
        uses: actions/setup-go@v4
        with:
            go-version-file: "middleware/go.mod"
            cache: true
            check-latest: true
        id: go
      - name: Compile the app.
        run: cd middleware/ && go build .
      - name: Run the app.
        run: cd middleware/ && ./csp-connector -help
