name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version-file: "middleware/go.mod"
        id: go
      - name: Get dependencies
        run: go get -v middleware/
      - name: Build Test
        run: go build -v middleware/
