name: Build the middleware application.
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version-file: "middleware/go.mod"
            cache: true
            check-latest: true
        id: go
      - name: Build the application
        run: cd middleware/ && go build .
      - name: Run the app help.
        run: ./middleware/csp-connector -help
      - name: Run the application.
        run: ./middleware/csp-connector -config=middleware/config.json
